#!/usr/bin/env python3
"""Generates StockRandomStreamVectors.cs from the SHIPPED libvstdlib.so.

vstdlib ships without sources -- only the shipped libvstdlib.so -- so the
golden sequences the unit tier compares StockRandomStream against are
drawn once from that binary by this script and checked in. The live-native
comparison (StockRandomStreamNativeTests) re-runs the same draws against the
library when it can be loaded, and skips visibly when it cannot.

Usage, from the repo root:
    python3 src/sourcesharp/managed/SourceSharp.Tests/MapTools/Rad/Ambient/gen_stock_random_vectors.py \
        > src/sourcesharp/managed/SourceSharp.Tests/MapTools/Rad/Ambient/StockRandomStreamVectors.cs

The draws are the same shapes the facts use: RandomFloat(0, 1) from a
default-constructed stream and from SetSeed(seed) for each seed below, and
RandomFloat(0, 1024) from a default-constructed stream. Each value is emitted as
its IEEE-754 bit pattern so no decimal round trip can hide a one-ulp slip.
"""

import ctypes
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, *([".."] * 7)))
LIB = os.path.join(REPO, "src", "lib", "public", "linux64")

COUNT = 512
SEEDS = [0, 1, 7, 12345, -3, 2147483647]


def load():
    ctypes.CDLL(os.path.join(LIB, "libtier0.so"), mode=ctypes.RTLD_GLOBAL)
    lib = ctypes.CDLL(os.path.join(LIB, "libvstdlib.so"), mode=ctypes.RTLD_GLOBAL)
    ctor = lib._ZN20CUniformRandomStreamC1Ev
    ctor.argtypes = [ctypes.c_void_p]
    ctor.restype = None
    seed = lib._ZN20CUniformRandomStream7SetSeedEi
    seed.argtypes = [ctypes.c_void_p, ctypes.c_int]
    seed.restype = None
    rf = lib._ZN20CUniformRandomStream11RandomFloatEff
    rf.argtypes = [ctypes.c_void_p, ctypes.c_float, ctypes.c_float]
    rf.restype = ctypes.c_float
    return ctor, seed, rf


def stream(ctor):
    buf = ctypes.create_string_buffer(1024)
    ctor(ctypes.byref(buf))
    return buf


def bits(value):
    return struct.unpack("<I", struct.pack("<f", value))[0]


def emit(name, values, out):
    out.write(f"    internal static ReadOnlySpan<uint> {name} =>\n    [\n")
    for i in range(0, len(values), 8):
        row = ", ".join(f"0x{bits(v):08X}" for v in values[i:i + 8])
        out.write(f"        {row},\n")
    out.write("    ];\n\n")


def main():
    ctor, seed, rf = load()
    out = sys.stdout
    out.write("// <auto-generated>\n")
    out.write("// Generated by gen_stock_random_vectors.py from the reference random\n")
    out.write("// stream. Do not edit by hand; re-run the script.\n")
    out.write("// </auto-generated>\n\n")
    out.write("namespace SourceSharp.Tests.MapTools.Rad.Ambient;\n\n")
    out.write("/// <summary>Golden CUniformRandomStream draws, as IEEE-754 bit patterns.</summary>\n")
    out.write("internal static class StockRandomStreamVectors\n{\n")
    out.write(f"    /// <summary>How many draws each sequence holds.</summary>\n")
    out.write(f"    internal const int Count = {COUNT};\n\n")

    s = stream(ctor)
    out.write("    /// <summary>RandomFloat(0, 1) from a default-constructed stream.</summary>\n")
    emit("DefaultUnit", [rf(ctypes.byref(s), 0.0, 1.0) for _ in range(COUNT)], out)

    s = stream(ctor)
    out.write("    /// <summary>RandomFloat(0, 1024) from a default-constructed stream.</summary>\n")
    emit("DefaultRanged1024", [rf(ctypes.byref(s), 0.0, 1024.0) for _ in range(COUNT)], out)

    for sd in SEEDS:
        s = stream(ctor)
        seed(ctypes.byref(s), sd)
        label = f"Seed{sd}".replace("-", "Minus")
        out.write(f"    /// <summary>RandomFloat(0, 1) after SetSeed({sd}).</summary>\n")
        emit(label, [rf(ctypes.byref(s), 0.0, 1.0) for _ in range(COUNT)], out)

    out.write("    /// <summary>The seeded sequences, by seed.</summary>\n")
    out.write("    /// <param name=\"seed\">One of the generated seeds.</param>\n")
    out.write("    /// <returns>The sequence.</returns>\n")
    out.write("    internal static ReadOnlySpan<uint> ForSeed(int seed) => seed switch\n    {\n")
    for sd in SEEDS:
        label = f"Seed{sd}".replace("-", "Minus")
        out.write(f"        {sd} => {label},\n")
    out.write("        _ => throw new ArgumentOutOfRangeException(nameof(seed), seed, \"not generated\"),\n")
    out.write("    };\n}\n")


if __name__ == "__main__":
    main()
