using System.Runtime.InteropServices;

using Xunit;

namespace SourceSharp.Tests.MapTools.Rad.Ambient;

/// <summary>
/// Where the shipped Valve libraries are, and whether this process can load them.
/// </summary>
/// <remarks>
/// <para>
/// vstdlib's SOURCE is not in the SDK; only the built <c>.so</c> is. The unit tier
/// therefore compares <c>StockRandomStream</c> against golden sequences drawn once
/// from that binary (<c>StockRandomStreamVectors</c>, generated by
/// <c>gen_stock_random_vectors.py</c>), and the LIVE comparison here is an extra
/// that runs only when the library can actually be loaded.
/// </para>
/// <para>
/// <b>Why it usually cannot be.</b> <c>libvstdlib.so</c> names
/// <c>libtier0.so</c> in its <c>DT_NEEDED</c>, and neither library carries a
/// <c>DT_SONAME</c>. glibc satisfies a <c>DT_NEEDED</c> entry from the
/// already-loaded list only by matching names, and an object loaded by absolute
/// path is known by that path -- so loading tier0 first by path does NOT satisfy
/// vstdlib's dependency, and the load fails with "libtier0.so: cannot open shared
/// object file" unless the directory is on <c>LD_LIBRARY_PATH</c> when the
/// process starts (glibc reads it once, at startup, so setting it from inside the
/// test is too late). This was the cause of the nine red facts the lane inherited:
/// the attribute found the files and let the bodies run, and the bodies could
/// never load them. The probe below performs the real load, so the facts SKIP
/// with that explanation instead.
/// </para>
/// <code>
/// LD_LIBRARY_PATH=$PWD/src/lib/public/linux64 dotnet test --filter StockRandomStreamNative
/// </code>
/// </remarks>
internal static class StockVstdlib
{
    /// <summary>The library, repo-relative.</summary>
    internal const string VstdlibPath = "src/lib/public/linux64/libvstdlib.so";

    /// <summary>Its dependency, repo-relative.</summary>
    internal const string Tier0Path = "src/lib/public/linux64/libtier0.so";

    /// <summary>Guards the one-time probe.</summary>
    private static readonly Lock ProbeLock = new();

    /// <summary>The probe's verdict, once taken.</summary>
    private static (bool Done, string? Skip, IntPtr Handle) _probe;

    /// <summary>Why a fact needing the libraries cannot run, or null.</summary>
    /// <returns>A skip reason, or null.</returns>
    internal static string? SkipReason() => Probe().Skip;

    /// <summary>The loaded <c>libvstdlib.so</c>.</summary>
    /// <returns>Its handle.</returns>
    /// <exception cref="InvalidOperationException">It could not be loaded.</exception>
    internal static IntPtr Handle() =>
        Probe() is { Skip: null } p
            ? p.Handle
            : throw new InvalidOperationException("the attribute should have skipped");

    /// <summary>Loads the libraries once and remembers how that went.</summary>
    /// <returns>The verdict.</returns>
    private static (bool Done, string? Skip, IntPtr Handle) Probe()
    {
        lock (ProbeLock)
        {
            if (!_probe.Done)
            {
                _probe = Load();
            }

            return _probe;
        }
    }

    /// <summary>Attempts the real load.</summary>
    /// <returns>The verdict.</returns>
    private static (bool Done, string? Skip, IntPtr Handle) Load()
    {
        if (!OperatingSystem.IsLinux())
        {
            return (true, "the shipped CUniformRandomStream is a Linux .so", IntPtr.Zero);
        }

        string? tier0 = RepoSourceFactAttribute.Find(Tier0Path);
        string? vstdlib = RepoSourceFactAttribute.Find(VstdlibPath);
        if (tier0 is null || vstdlib is null)
        {
            return (true, $"{VstdlibPath} or {Tier0Path} is not above this binary", IntPtr.Zero);
        }

        if (!NativeLibrary.TryLoad(tier0, out _) || !NativeLibrary.TryLoad(vstdlib, out IntPtr handle))
        {
            return (true,
                "libvstdlib.so could not be loaded: its DT_NEEDED libtier0.so has no SONAME, so "
                + "glibc resolves it only through LD_LIBRARY_PATH read at process start. Run with "
                + "LD_LIBRARY_PATH=<repo>/src/lib/public/linux64 to compare against the live "
                + "library; the golden-vector facts in StockRandomStreamTests cover the unit tier.",
                IntPtr.Zero);
        }

        return (true, null, handle);
    }
}

/// <summary>A <see cref="FactAttribute"/> that skips, visibly, without a loadable vstdlib.</summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class VstdlibFactAttribute : FactAttribute
{
    /// <summary>Decides at discovery whether the library loads.</summary>
    public VstdlibFactAttribute() => Skip = StockVstdlib.SkipReason();
}

/// <summary>A <see cref="TheoryAttribute"/> that skips, visibly, without a loadable vstdlib.</summary>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
public sealed class VstdlibTheoryAttribute : TheoryAttribute
{
    /// <summary>Decides at discovery whether the library loads.</summary>
    public VstdlibTheoryAttribute() => Skip = StockVstdlib.SkipReason();
}

/// <summary>
/// A live <c>CUniformRandomStream</c> inside the shipped <c>libvstdlib.so</c>.
/// </summary>
/// <remarks>
/// The object is a block of native memory the library's OWN constructor is run
/// over, so the class layout does not have to be described -- only made big
/// enough. The entry points are the Itanium-ABI mangled names, bound through
/// <see cref="NativeLibrary.GetExport"/> on the handle the probe loaded (a
/// <c>DllImport</c> by file name would probe the loader's search path again and
/// miss).
/// </remarks>
internal sealed unsafe class NativeUniformRandomStream : IDisposable
{
    /// <summary>How much memory to give the object.</summary>
    private const int ObjectSize = 1024;

    /// <summary>The object.</summary>
    private readonly IntPtr _self;

    /// <summary><c>SetSeed(int)</c>.</summary>
    private readonly delegate* unmanaged<IntPtr, int, void> _setSeed;

    /// <summary><c>RandomFloat(float, float)</c>.</summary>
    private readonly delegate* unmanaged<IntPtr, float, float, float> _randomFloat;

    /// <summary>Whether it has been freed.</summary>
    private bool _disposed;

    /// <summary>Constructs a stream the way <c>CLeafSampler</c> does.</summary>
    private NativeUniformRandomStream()
    {
        IntPtr lib = StockVstdlib.Handle();
        var construct = (delegate* unmanaged<IntPtr, void>)NativeLibrary.GetExport(
            lib, "_ZN20CUniformRandomStreamC1Ev");
        _setSeed = (delegate* unmanaged<IntPtr, int, void>)NativeLibrary.GetExport(
            lib, "_ZN20CUniformRandomStream7SetSeedEi");
        _randomFloat = (delegate* unmanaged<IntPtr, float, float, float>)NativeLibrary.GetExport(
            lib, "_ZN20CUniformRandomStream11RandomFloatEff");

        _self = (IntPtr)NativeMemory.AllocZeroed(ObjectSize);
        construct(_self);
    }

    /// <summary>Constructs a default stream.</summary>
    /// <returns>The stream.</returns>
    public static NativeUniformRandomStream Create() => new();

    /// <summary>Reseeds it.</summary>
    /// <param name="seed">The seed.</param>
    public void SetSeed(int seed) => _setSeed(_self, seed);

    /// <summary>Draws a float.</summary>
    /// <param name="low">The lower bound.</param>
    /// <param name="high">The upper bound.</param>
    /// <returns>The draw.</returns>
    public float RandomFloat(float low, float high) => _randomFloat(_self, low, high);

    /// <inheritdoc />
    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        NativeMemory.Free((void*)_self);
        _disposed = true;
    }
}
