//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Inspired by and based on the Half-Life 2 Source SDK 2013 by Valve:
// https://github.com/ValveSoftware/source-sdk-2013
//
//=============================================================================//

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Xunit;

namespace SourceSharp.Tests;

/// <summary>
/// Every C# file in the tree starts with the Source SDK 2013 copyright header.
/// </summary>
/// <remarks>
/// <para>
/// CLAUDE.md asks for the header on every file, and review found five files
/// without it: one library file and four tests, all added together. A rule
/// that is only written down drifts like that, so this reads the files.
/// </para>
/// <para>
/// It reads the sources, not the built assemblies, so it needs the tree above
/// the test binary and skips (rather than passes) without it. It covers
/// <c>src/</c> and <c>tools/</c>, the two places C# lives, and leaves out
/// <c>bin/</c> and <c>obj/</c>, where the build writes generated files of
/// its own.
/// </para>
/// </remarks>
public sealed class CopyrightHeaderTests
{
    /// <summary>The header, line by line, exactly as the files carry it.</summary>
    private const string Header =
        "//========= Copyright Valve Corporation, All rights reserved. ============//\n"
        + "//\n"
        + "// Inspired by and based on the Half-Life 2 Source SDK 2013 by Valve:\n"
        + "// https://github.com/ValveSoftware/source-sdk-2013\n"
        + "//\n"
        + "//=============================================================================//\n";

    /// <summary>
    /// Files written by a generator rather than by hand, and why each has no
    /// header: the generator writes an <c>&lt;auto-generated&gt;</c> banner on
    /// the first line instead, which tells analyzers and editors to leave the
    /// file alone, and a header added by hand would be lost on the next run.
    /// Each entry must still exist and still carry that banner, so the list
    /// cannot outlive the file it excuses.
    /// </summary>
    private static readonly IReadOnlyDictionary<string, string> Generated = new Dictionary<string, string>
    {
        ["src/SourceSharp.Tests/MapTools/Rad/Ambient/StockRandomStreamVectors.cs"] =
            "golden random-stream draws written by gen_stock_random_vectors.py; "
            + "regenerated, never edited by hand",
    };

    [RepoSourceFact("src/SourceSharp.MapTools.slnx")]
    public void EveryCSharpFileStartsWithTheHeader()
    {
        string root = RepoRoot();
        string[] missing = [.. SourceFiles(root)
            .Where(relative => !Generated.ContainsKey(relative))
            .Where(relative => !Normalised(Path.Combine(root, relative)).StartsWith(Header, StringComparison.Ordinal))
            .Order(StringComparer.Ordinal)];

        Assert.True(missing.Length == 0,
            "these files do not start with the Source SDK 2013 copyright header (copy it from any other file):\n  "
            + string.Join("\n  ", missing));
    }

    [RepoSourceFact("src/SourceSharp.MapTools.slnx")]
    public void EveryExemptFileExistsAndIsStillGenerated()
    {
        string root = RepoRoot();
        foreach ((string relative, string reason) in Generated)
        {
            string path = Path.Combine(root, relative);
            Assert.True(File.Exists(path), $"{relative} is listed as generated ({reason}) but no longer exists");
            Assert.StartsWith("// <auto-generated>", Normalised(path), StringComparison.Ordinal);
        }
    }

    [RepoSourceFact("src/SourceSharp.MapTools.slnx")]
    public void TheScanFindsTheTreesFiles()
    {
        // A scan that found nothing would pass the header fact vacuously.
        string[] files = [.. SourceFiles(RepoRoot())];

        Assert.Contains("src/SourceSharp.Tests/CopyrightHeaderTests.cs", files);
        Assert.Contains(files, f => f.StartsWith("tools/", StringComparison.Ordinal));
        Assert.DoesNotContain(files, f => f.Contains("/obj/", StringComparison.Ordinal)
                                          || f.Contains("/bin/", StringComparison.Ordinal));
    }

    private static string RepoRoot() =>
        Path.GetDirectoryName(Path.GetDirectoryName(RepoSourceFactAttribute.Find("src/SourceSharp.MapTools.slnx"))!)!;

    /// <summary>The repo-relative, forward-slash paths of every .cs file under src/ and tools/.</summary>
    private static IEnumerable<string> SourceFiles(string root)
    {
        foreach (string top in new[] { "src", "tools" })
        {
            string dir = Path.Combine(root, top);
            if (!Directory.Exists(dir))
            {
                continue;
            }

            foreach (string path in Directory.EnumerateFiles(dir, "*.cs", SearchOption.AllDirectories))
            {
                string relative = Path.GetRelativePath(root, path).Replace('\\', '/');
                string[] parts = relative.Split('/');
                if (parts.Contains("bin") || parts.Contains("obj"))
                {
                    continue;
                }

                yield return relative;
            }
        }
    }

    /// <summary>
    /// The file's text with a byte-order mark dropped and CRLF read as LF: a
    /// Windows checkout with autocrlf has CRLF endings, and the header is the
    /// same header either way.
    /// </summary>
    private static string Normalised(string path) =>
        File.ReadAllText(path).TrimStart('﻿').Replace("\r\n", "\n", StringComparison.Ordinal);
}
