//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Inspired by and based on the Half-Life 2 Source SDK 2013 by Valve:
// https://github.com/ValveSoftware/source-sdk-2013
//
//=============================================================================//

using System.Collections.Concurrent;

using SourceSharp.MapTools.Rooms;

using Xunit;

namespace SourceSharp.Tests.MapTools.Rooms;

/// <summary>
/// The height-aware generator (the rooms design, 17.9, for one-cell rooms
/// since D30): large rooms, those taller than their cell, stand only in
/// groups of adjacent large rooms grown from their own sequence, each group
/// joined inside and reached through standard rooms; <c>-max-height</c>
/// drops rooms outright; and without a large share nothing any seed made
/// before moves.
/// </summary>
public sealed class LevelGeneratorHeightsTests
{
    /// <summary>A kit whose door leaves room for rooms lower than the cell (at least 128 tall).</summary>
    private static readonly SocketKit Kit = new(96, 96, 16);

    private const float Cell = 256;

    private static readonly RoomFacing[] All = [RoomFacing.PositiveX, RoomFacing.NegativeX, RoomFacing.PositiveY, RoomFacing.NegativeY];

    private static RoomDefinition Kind(string name, float height, params RoomFacing[] sockets) =>
        new RoomDefinition(name, Cell, Kit, [.. sockets.Select(f => new RoomSocket(f, RoomLibraryVmf.WallName(f)))]) with { Height = height };

    /// <summary>The 3x3 sample's five kinds at one height.</summary>
    private static RoomDefinition[] Kinds(string prefix, float height) =>
    [
        Kind(prefix + "cross", height, All),
        Kind(prefix + "tee", height, RoomFacing.PositiveX, RoomFacing.NegativeX, RoomFacing.PositiveY),
        Kind(prefix + "corner", height, RoomFacing.PositiveX, RoomFacing.PositiveY),
        Kind(prefix + "hall", height, RoomFacing.PositiveX, RoomFacing.NegativeX),
        Kind(prefix + "end", height, RoomFacing.PositiveX),
    ];

    /// <summary>Standard kinds, with two sets of tall kinds (two and four cells of height) between and after them in library order.</summary>
    private static RoomDefinition[] Mixed() =>
    [
        .. Kinds(string.Empty, Cell).Take(2),
        .. Kinds("hi_", 512),
        .. Kinds(string.Empty, Cell).Skip(2),
        .. Kinds("top_", 1024),
    ];

    private static string Write(LevelGrid level) => LevelYaml.Write(level, []);

    private static string Outcome(Func<LevelGrid> generate)
    {
        try
        {
            return Write(generate());
        }
        catch (LinkException exception)
        {
            return "refused: " + exception.Message;
        }
    }

    // ---- nothing moves without a large share -----------------------------------------------------

    /// <summary>
    /// A library that gains tall rooms generates, at a large share of 0,
    /// exactly the levels (and refusals) it generated without them, as the
    /// frozen old generator made them: the tall rooms are dropped before any
    /// draw, wherever they sit in library order. Explicit defaults (a share
    /// of 0, another group size, a height limit no room reaches) change
    /// nothing either.
    /// </summary>
    [Fact]
    public void WithoutALargeShareEveryLevelIsTheOldOne()
    {
        RoomDefinition[] standard = Kinds(string.Empty, Cell);
        RoomDefinition[] mixed = Mixed();
        int compared = 0;
        foreach ((int rows, int columns) in new[] { (1, 1), (1, 3), (2, 2), (3, 3), (4, 5), (6, 6), (8, 3) })
        {
            foreach (double empty in new[] { 0, 0.3, 0.6 })
            {
                for (ulong seed = 0; seed < 12; seed++)
                {
                    LevelGeneratorOptions options = new(rows, columns, seed, empty);
                    string old = Outcome(() => LegacyLevelGenerator.Generate(standard, options, "l", "x"));
                    Assert.Equal(old, Outcome(() => LevelGenerator.Generate(standard, options, "l", "x")));
                    Assert.Equal(old, Outcome(() => LevelGenerator.Generate(mixed, options, "l", "x")));
                    Assert.Equal(old, Outcome(() => LevelGenerator.Generate(
                        standard, options with { LargeShare = 0, GroupSize = 7, MaxHeight = 4096 }, "l", "x")));
                    compared++;
                }
            }
        }

        Assert.Equal(7 * 3 * 12, compared);
    }

    /// <summary>The header names the large share and the height limit only when they are used.</summary>
    [Fact]
    public void TheHeaderNamesTheLargeShareOnlyWhenItIsUsed()
    {
        LevelGeneratorOptions plain = new(3, 3, 5);
        LevelGrid level = LevelGenerator.Generate(Mixed(), plain, "l", "x");
        Assert.Equal("generated by ssmap layout: seed 5, 3 rows x 3 columns, 0 empty cell(s)", LevelGenerator.Header(plain, level)[0]);

        LevelGeneratorOptions large = plain with { LargeShare = 0.25, GroupSize = 2 };
        Assert.Equal(
            "generated by ssmap layout: seed 5, 3 rows x 3 columns, 0 empty cell(s), large share 0.25, groups of 2",
            LevelGenerator.Header(large, LevelGenerator.Generate(Mixed(), large, "l", "x"))[0]);

        LevelGeneratorOptions low = plain with { MaxHeight = 600 };
        Assert.Equal(
            "generated by ssmap layout: seed 5, 3 rows x 3 columns, 0 empty cell(s), rooms at most 600 tall",
            LevelGenerator.Header(low, level)[0]);
    }

    // ---- the height limit ------------------------------------------------------------------------

    /// <summary>
    /// <c>-max-height</c> drops every room taller than it, standard or
    /// large: a limit below the cell leaves only the low hallways, and a
    /// large share then draws its groups only from the large rooms within
    /// the limit.
    /// </summary>
    [Fact]
    public void AHeightLimitDropsTallerRooms()
    {
        RoomDefinition[] rooms = [.. Mixed(), .. Kinds("low_", 128)];
        Dictionary<string, RoomDefinition> byName = rooms.ToDictionary(r => r.Name);
        for (ulong seed = 0; seed < 20; seed++)
        {
            LevelGrid low = LevelGenerator.Generate(rooms, new LevelGeneratorOptions(4, 4, seed) { MaxHeight = 200 }, "l", "x");
            Assert.All(low.Placed, p => Assert.Equal(128, byName[p.Cell.Room].Height));

            LevelGrid mid = LevelGenerator.Generate(rooms, new LevelGeneratorOptions(4, 4, seed) { MaxHeight = 600, LargeShare = 0.4 }, "l", "x");
            Assert.All(mid.Placed, p => Assert.True(byName[p.Cell.Room].Height <= 600));
            Assert.Contains(mid.Placed, p => byName[p.Cell.Room].Height == 512);
        }
    }

    /// <summary>
    /// A library whose every room with a socket is too tall for the fill is
    /// refused saying why: taller than the cell, or than the limit.
    /// </summary>
    [Fact]
    public void RoomsTooTallForTheFillAreRefusedSayingWhy()
    {
        LinkException tall = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(Kinds("hi_", 512), new LevelGeneratorOptions(2, 2, 1), "l", "x"));
        Assert.Equal(
            "none of the library's 5 room(s) has a socket and stands no taller than its cell, so 4 rooms cannot be joined;"
            + " a room taller than its cell stands only in a group of large rooms (-large).",
            tall.Message);

        LinkException limited = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(Kinds(string.Empty, Cell), new LevelGeneratorOptions(2, 2, 1) { MaxHeight = 200 }, "l", "x"));
        Assert.Equal(
            "none of the library's 5 room(s) has a socket and stands no taller than its cell and 200 (-max-height), so 4 rooms cannot be joined;"
            + " a room taller than its cell stands only in a group of large rooms (-large).",
            limited.Message);

        // Rooms without sockets keep their old message, heights or not.
        LinkException boxes = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate([Kind("box", 512), Kind("cube", Cell)], new LevelGeneratorOptions(1, 2, 1), "l", "x"));
        Assert.Equal("none of the library's 2 room(s) has a socket, so 2 rooms cannot be joined.", boxes.Message);
    }

    // ---- the groups ------------------------------------------------------------------------------

    /// <summary>
    /// The rule for every level with large rooms, over shapes, empty shares,
    /// large shares, group sizes and seeds: the large rooms cover exactly
    /// <c>floor(share × occupied)</c> cells; they stand in groups of at most
    /// the group size, no two groups sharing a wall; each group is joined
    /// inside through its own sockets; every wall shared by two rooms has a
    /// socket on both sides or neither; and a player reaches every room
    /// from every other, so every group is reached through standard rooms.
    /// </summary>
    [Fact]
    public void EveryLevelWithLargeRoomsHoldsTheGroupRules()
    {
        RoomDefinition[] rooms = Mixed();
        Dictionary<string, RoomDefinition> byName = rooms.ToDictionary(r => r.Name);
        int levels = 0, groups = 0, multi = 0;
        foreach ((int rows, int columns) in new[] { (2, 3), (3, 3), (4, 4), (5, 6), (8, 8) })
        {
            foreach ((double empty, double share, int group) in new[] { (0.0, 0.3, 3), (0.2, 0.5, 4), (0.3, 0.2, 1), (0.0, 0.6, 6) })
            {
                for (ulong seed = 0; seed < 8; seed++)
                {
                    LevelGeneratorOptions options = new(rows, columns, seed, empty) { LargeShare = share, GroupSize = group };
                    LevelGrid level;
                    try
                    {
                        level = LevelGenerator.Generate(rooms, options, "l", "x");
                    }
                    catch (LinkException exception) when (exception.Message.StartsWith("layout: no level of", StringComparison.Ordinal))
                    {
                        continue;
                    }

                    int occupied = level.Cells.Count(c => c is not null);
                    List<List<(int X, int Y)>> found = Groups(level, byName);
                    Assert.Equal((int)Math.Floor(share * occupied), found.Sum(g => g.Count));
                    Assert.All(found, g => Assert.InRange(g.Count, 1, group));
                    foreach (List<(int X, int Y)> g in found)
                    {
                        AssertJoinedInside(level, byName, g);
                    }

                    AssertLinesUp(level, byName);
                    RoomLinter.CheckReachable(level.ToLayout(n => byName[n], Cell, Kit), n => byName[n]);
                    groups += found.Count;
                    multi += found.Count(g => g.Count > 1);
                    levels++;
                }
            }
        }

        // Most of the grid asks make a level, and groups of several rooms are common.
        Assert.True(levels > 120, $"{levels} levels");
        Assert.True(multi > groups / 4, $"{multi} of {groups} groups hold more than one room");
    }

    /// <summary>
    /// Heights cluster: over many seeds, rooms that share a group are nearly
    /// always of one height, although the library offers two tall heights
    /// in equal numbers (a random choice would match about half the time).
    /// </summary>
    [Fact]
    public void GroupsGatherRoomsOfOneHeight()
    {
        RoomDefinition[] rooms = Mixed();
        Dictionary<string, RoomDefinition> byName = rooms.ToDictionary(r => r.Name);
        int pairs = 0, same = 0;
        for (ulong seed = 0; seed < 60; seed++)
        {
            LevelGrid level = LevelGenerator.Generate(rooms, new LevelGeneratorOptions(6, 6, seed) { LargeShare = 0.4, GroupSize = 4 }, "l", "x");
            foreach (List<(int X, int Y)> group in Groups(level, byName))
            {
                float first = byName[level[group[0].X, group[0].Y]!.Room].Height;
                foreach ((int x, int y) in group.Skip(1))
                {
                    pairs++;
                    same += byName[level[x, y]!.Room].Height == first ? 1 : 0;
                }
            }
        }

        Assert.True(pairs > 100, $"{pairs} pairs");
        Assert.True(same >= pairs * 0.95, $"{same} of {pairs} grouped rooms share their group's height");
    }

    /// <summary>
    /// The groups draw from their own sequence: the same seed gives the same
    /// file on every run and on many threads at once, and the empty cells,
    /// drawn from the main sequence first, are the ones the level has
    /// without a large share.
    /// </summary>
    [Fact]
    public void LargeLevelsAreTheSameOnEveryThread()
    {
        RoomDefinition[] rooms = Mixed();
        LevelGeneratorOptions options = new(6, 7, 31, 0.25) { LargeShare = 0.35 };
        string expected = Write(LevelGenerator.Generate(rooms, options, "l", "x"));
        ConcurrentBag<string> runs = [];
        System.Threading.Tasks.Parallel.For(0, 16, new ParallelOptions { MaxDegreeOfParallelism = 4 }, _ => runs.Add(Write(LevelGenerator.Generate(rooms, options, "l", "x"))));
        Assert.All(runs, run => Assert.Equal(expected, run));

        LevelGrid plain = LevelGenerator.Generate(rooms, options with { LargeShare = 0 }, "l", "x");
        LevelGrid large = LevelGenerator.Generate(rooms, options, "l", "x");
        Assert.Equal(plain.Cells.Select(c => c is null), large.Cells.Select(c => c is null));
        Assert.NotEqual(Write(plain), Write(large));
    }

    /// <summary>
    /// Role rooms stay out of the groups and the groups leave them room: a
    /// level of every cell but the two role cells large keeps both roles
    /// (the share is capped below the cells the roles need), and a tall role
    /// room is never placed, being neither a standard room nor a group's.
    /// </summary>
    [Fact]
    public void RoleRoomsStandOutsideTheGroups()
    {
        RoomDefinition[] rooms =
        [
            .. Kinds(string.Empty, Cell),
            Kind("up", Cell, All),
            Kind("down", Cell, All),
            Kind("tall_up", 512, All),
            .. Kinds("hi_", 512),
        ];
        RoomRole[] roles = [.. rooms.Select(r => r.Name switch { "up" or "tall_up" => RoomRole.Up, "down" => RoomRole.Down, _ => RoomRole.None })];
        Dictionary<string, RoomDefinition> byName = rooms.ToDictionary(r => r.Name);
        for (ulong seed = 0; seed < 20; seed++)
        {
            LevelGrid level = LevelGenerator.Generate(
                rooms, new LevelGeneratorOptions(3, 3, seed) { LargeShare = 0.5, GroupSize = 9 }, "l", "x", null, new LayoutTransitions(roles));
            Assert.Single(level.Placed, p => p.Cell.Room == "up");
            Assert.Single(level.Placed, p => p.Cell.Room == "down");
            Assert.DoesNotContain(level.Placed, p => p.Cell.Room == "tall_up");
            Assert.Equal(4, level.Placed.Count(p => LevelGenerator.IsLarge(byName[p.Cell.Room])));
        }
    }

    /// <summary>
    /// A budget counts the large rooms too: they are spent before the fill
    /// starts, so a budget that fits the level's standard rooms and not its
    /// large ones is refused before any search, naming what they bring.
    /// </summary>
    [Fact]
    public void ABudgetCountsTheLargeRooms()
    {
        RoomDefinition[] rooms = [.. Kinds(string.Empty, Cell), .. Kinds("hi_", 512)];
        int[] costs = [1, 1, 1, 1, 1, 50, 50, 50, 50, 50];
        LevelGeneratorOptions options = new(3, 3, 4) { LargeShare = 0.25 };

        // Two large rooms (floor(0.25 x 9)) at 50 each, seven standard at 1, the worldspawn: 108.
        LevelGrid fits = LevelGenerator.Generate(rooms, options, "l", "x", new LayoutEntityBudget(108, costs));
        Assert.Equal(2, fits.Placed.Count(p => p.Cell.Room.StartsWith("hi_", StringComparison.Ordinal)));

        LinkException over = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(rooms, options, "l", "x", new LayoutEntityBudget(107, costs)));
        Assert.Equal(
            "no level of 3x3 cells keeps within the entity budget of 107 edicts: its 9 room(s) bring at least 108, the worldspawn included.",
            over.Message);
    }

    /// <summary>
    /// 17.3's two refusals: a large share with no large room to draw (none
    /// at all, or none within the height limit), and a share no pass of the
    /// area sequence covers (one-socket rooms cannot join a group, and
    /// groups of one cannot touch, so four of five cells in a row is out of
    /// reach).
    /// </summary>
    [Fact]
    public void ALargeShareThatCannotBeMetIsRefused()
    {
        LinkException none = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(Kinds(string.Empty, Cell), new LevelGeneratorOptions(3, 3, 1) { LargeShare = 0.3 }, "l", "x"));
        Assert.Equal("layout: -large asks for large areas, but no library of the level has a room taller than one cell.", none.Message);

        LinkException limited = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(Mixed(), new LevelGeneratorOptions(3, 3, 1) { LargeShare = 0.3, MaxHeight = 300 }, "l", "x"));
        Assert.Equal(
            "layout: -large asks for large areas, but no library of the level has a room taller than one cell and at most 300 tall (-max-height).",
            limited.Message);

        RoomDefinition[] rooms = [.. Kinds(string.Empty, Cell), Kind("hi_end", 512, RoomFacing.PositiveX)];
        LinkException crowded = Assert.Throws<LinkException>(
            () => LevelGenerator.Generate(rooms, new LevelGeneratorOptions(1, 5, 9) { LargeShare = 0.8 }, "l", "x"));
        Assert.Equal(
            "layout: no level of 1x5 with seed 9 covers 4 cells with large rooms in groups of 3; lower -large or grow the grid.",
            crowded.Message);
    }

    /// <summary>The large settings are checked with the rest of the options, before any library is read.</summary>
    [Fact]
    public void TheLargeSettingsAreChecked()
    {
        LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { LargeShare = 0.999, GroupSize = 1, MaxHeight = 1 });
        ArgumentException share = Assert.Throws<ArgumentException>(
            () => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { LargeShare = 1 }));
        Assert.Equal("the large share 1 is not in [0, 1) (Parameter 'options')", share.Message);
        Assert.Throws<ArgumentException>(() => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { LargeShare = -0.5 }));
        Assert.Throws<ArgumentException>(() => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { LargeShare = double.NaN }));
        ArgumentException group = Assert.Throws<ArgumentException>(
            () => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { GroupSize = 0 }));
        Assert.Equal("a group of 0 large rooms is not 1 or more (Parameter 'options')", group.Message);
        ArgumentException height = Assert.Throws<ArgumentException>(
            () => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { MaxHeight = 0 }));
        Assert.Equal("the most height 0 is not a positive number of units (Parameter 'options')", height.Message);
        Assert.Throws<ArgumentException>(() => LevelGenerator.CheckOptions(new LevelGeneratorOptions(2, 2, 1) { MaxHeight = float.PositiveInfinity }));
        Assert.Throws<ArgumentException>(() => LevelGenerator.Generate(Mixed(), new LevelGeneratorOptions(2, 2, 1) { GroupSize = -1 }, "l", "x"));
    }

    // ---- the pieces ------------------------------------------------------------------------------

    /// <summary>A room is large only when taller than its cell; a cube and a low hallway are standard.</summary>
    [Fact]
    public void LargeMeansTallerThanTheCell()
    {
        Assert.True(LevelGenerator.IsLarge(Kind("a", 257)));
        Assert.False(LevelGenerator.IsLarge(Kind("b", Cell)));
        Assert.False(LevelGenerator.IsLarge(Kind("c", 128)));
        Assert.Throws<ArgumentNullException>(() => LevelGenerator.IsLarge(null!));
    }

    /// <summary>The grouping's key counts whole cells of height either way, so 511 above a 256 room is one step and 512 two.</summary>
    [Theory]
    [InlineData(512f, 512f, 0)]
    [InlineData(767f, 512f, 0)]
    [InlineData(768f, 512f, 1)]
    [InlineData(256f, 768f, 2)]
    [InlineData(1024f, 512f, 2)]
    public void TheHeightKeyCountsWholeCells(float height, float first, int steps) =>
        Assert.Equal(steps, LevelGenerator.HeightSteps(height, first, Cell));

    /// <summary>
    /// The walls left once large rooms stand must still join every occupied
    /// cell: a tall room without a socket towards the rest walls it off, and
    /// the same room with one does not.
    /// </summary>
    [Fact]
    public void LargeRoomsMustLeaveTheCellsJoined()
    {
        // Three cells in a row, the middle large; masks by candidate: 0 has
        // east and west sockets, 1 only east.
        bool[] occupied = [true, true, true];
        int[] maskOf = [1 | 2, 1];
        Assert.True(LevelGenerator.Joined(occupied, [-1, 0, -1], maskOf, 1, 3));
        Assert.False(LevelGenerator.Joined(occupied, [-1, 1, -1], maskOf, 1, 3));
        Assert.True(LevelGenerator.Joined(occupied, [-1, -1, -1], maskOf, 1, 3));
        Assert.True(LevelGenerator.Joined([false, false], [-1, -1], maskOf, 1, 2));
    }

    /// <summary>The large rooms of a level, grouped by shared walls, each group in cell order.</summary>
    private static List<List<(int X, int Y)>> Groups(LevelGrid level, Dictionary<string, RoomDefinition> byName)
    {
        bool Large(int x, int y) =>
            x >= 0 && y >= 0 && x < level.Columns && y < level.Rows && level[x, y] is { } cell && LevelGenerator.IsLarge(byName[cell.Room]);

        HashSet<(int, int)> seen = [];
        List<List<(int X, int Y)>> groups = [];
        for (int y = 0; y < level.Rows; y++)
        {
            for (int x = 0; x < level.Columns; x++)
            {
                if (!Large(x, y) || !seen.Add((x, y)))
                {
                    continue;
                }

                List<(int X, int Y)> group = [(x, y)];
                for (int i = 0; i < group.Count; i++)
                {
                    foreach ((int dx, int dy) in new[] { (1, 0), (-1, 0), (0, 1), (0, -1) })
                    {
                        (int nx, int ny) = (group[i].X + dx, group[i].Y + dy);
                        if (Large(nx, ny) && seen.Add((nx, ny)))
                        {
                            group.Add((nx, ny));
                        }
                    }
                }

                groups.Add(group);
            }
        }

        return groups;
    }

    /// <summary>The world walls a placed room has sockets on, as (dx, dy) steps.</summary>
    private static HashSet<(int, int)> Sockets(LevelGrid level, Dictionary<string, RoomDefinition> byName, int x, int y)
    {
        LevelCell cell = level[x, y]!;
        RoomTransform transform = new(new RoomPlacement(cell.Room, 0, 0, cell.Rotation), 1f);
        HashSet<(int, int)> steps = [];
        foreach (RoomSocket socket in byName[cell.Room].Sockets)
        {
            (int axis, int sign) = transform.WorldNormal(socket.Facing);
            steps.Add(axis == 0 ? (sign, 0) : (0, sign));
        }

        return steps;
    }

    /// <summary>A group's rooms reach one another through their own joints alone.</summary>
    private static void AssertJoinedInside(LevelGrid level, Dictionary<string, RoomDefinition> byName, List<(int X, int Y)> group)
    {
        HashSet<(int, int)> members = [.. group];
        HashSet<(int, int)> reached = [group[0]];
        Queue<(int X, int Y)> queue = new([group[0]]);
        while (queue.Count > 0)
        {
            (int x, int y) = queue.Dequeue();
            foreach ((int dx, int dy) in Sockets(level, byName, x, y))
            {
                (int nx, int ny) = (x + dx, y + dy);
                if (members.Contains((nx, ny)) && Sockets(level, byName, nx, ny).Contains((-dx, -dy)) && reached.Add((nx, ny)))
                {
                    queue.Enqueue((nx, ny));
                }
            }
        }

        Assert.Equal(members.Count, reached.Count);
    }

    /// <summary>Every wall shared by two rooms has a socket on both sides or on neither.</summary>
    private static void AssertLinesUp(LevelGrid level, Dictionary<string, RoomDefinition> byName)
    {
        foreach ((int x, int y, _) in level.Placed)
        {
            HashSet<(int, int)> here = Sockets(level, byName, x, y);
            foreach ((int dx, int dy) in new[] { (1, 0), (0, 1) })
            {
                (int nx, int ny) = (x + dx, y + dy);
                if (nx < level.Columns && ny < level.Rows && level[nx, ny] is not null)
                {
                    Assert.Equal(here.Contains((dx, dy)), Sockets(level, byName, nx, ny).Contains((-dx, -dy)));
                }
            }
        }
    }
}
